project_id = "nivtcbteowgvkiqikptr"

[functions.create-reward-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.process-gibrapay-payout]
verify_jwt = false

[functions.check-gibrapay-balance]
verify_jwt = false

[functions.request-gibrapay-payment]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
